name: apiRestInvoiceTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install composer
      run: composer install

    - name: Run phpstan
      run: ./vendor/bin/phpstan analyse src --level 3



